package com.databricks.jdbc.model.telemetry.enums;

public enum DatabricksDriverErrorCode {
  CONNECTION_ERROR(1001),
  CHUNK_DOWNLOAD_ERROR(1002),
  EXECUTE_STATEMENT_FAILED(1003),
  EXECUTE_STATEMENT_CANCELLED(1008),
  RESULT_SET_ERROR(1004),
  UNSUPPORTED_OPERATION(1005),
  NOT_IMPLEMENTED_OPERATION(1006),
  STATEMENT_EXECUTION_TIMEOUT(1007),
  STATEMENT_CLOSED(1009),
  CONNECTION_CLOSED(1010),
  LOGGING_INITIALISATION_ERROR(1011),
  RESULT_SET_CLOSED(1012),
  VOLUME_OPERATION_PARSING_ERROR(1013),
  THREAD_INTERRUPTED_ERROR(1014),
  INPUT_VALIDATION_ERROR(1015),
  COMPLEX_DATA_TYPE_STRUCT_CONVERSION_ERROR(1016),
  COMPLEX_DATA_TYPE_ARRAY_CONVERSION_ERROR(1017),
  COMPLEX_DATA_TYPE_MAP_CONVERSION_ERROR(1018),
  INVALID_STATE(1019),
  INLINE_CHUNK_PARSING_ERROR(1020),
  DECOMPRESSION_ERROR(1021),
  VOLUME_OPERATION_URL_GENERATION_ERROR(1022),
  VOLUME_OPERATION_LOCAL_FILE_EXISTS_ERROR(1023),
  VOLUME_OPERATION_EXCEPTION(1024),
  VOLUME_OPERATION_PUT_OPERATION_EXCEPTION(1025),
  VOLUME_OPERATION_DELETE_OPERATION_EXCEPTION(1026),
  VOLUME_OPERATION_FILE_DOWNLOAD_ERROR(1027),
  VOLUME_OPERATION_INVALID_STATE(1028),
  SESSION_ID_PARSING_EXCEPTION(1029),
  BATCH_EXECUTE_EXCEPTION(1030),
  TEMPORARY_REDIRECT_EXCEPTION(1031),
  JSON_PARSING_ERROR(1032),
  CATALOG_OR_SCHEMA_FETCH_ERROR(1033),
  INTEGRATION_TEST_ERROR(1034),
  SDK_CLIENT_ERROR(1035),
  OPERATION_TIMEOUT_ERROR(1036),
  SSL_HANDSHAKE_ERROR(1037),
  AUTH_ERROR(1038),
  INVALID_CHUNK_STATE_TRANSITION(1039),
  CHUNK_READY_ERROR(1040),
  TRANSACTION_SET_AUTOCOMMIT_ERROR(1041),
  TRANSACTION_COMMIT_ERROR(1042),
  TRANSACTION_ROLLBACK_ERROR(1043),
  RATE_LIMIT_EXCEEDED(1044),
  ARROW_SCHEMA_PARSING_ERROR(22000);

  private final int code;

  DatabricksDriverErrorCode(int code) {
    this.code = code;
  }

  public int getCode() {
    return code;
  }
}
